sudo: enabled
dist: xenial

language: minimal

# The recommended and tested build environment is Debian, so hack travis to
# be a Debian Stretch install
before_install:
    - sudo dpkg -P wireless-regdb crda linux-image-extra-4.4.0-138-generic linux-image-generic linux-image-generic-lts-xenial
    - sudo apt-get install -y debian-archive-keyring
    - sudo rm -f /etc/apt/sources.list.d/*
    - echo "deb http://httpredir.debian.org/debian/ stretch main" |sudo tee /etc/apt/sources.list
    - sudo apt-get update
    - sudo apt-get dist-upgrade -y

install:
    - make build-depends

script:
    - make test CONFIG_DISABLE_KVM=yes
