sudo: enabled
dist: bionic

language: minimal

install:
    - sudo apt-get update
    - make build-depends
    - echo "deb http://archive.ubuntu.com/ubuntu cosmic main restricted" | sudo tee /etc/apt/sources.list.d/cosmic.list
    - sudo apt-get update
    - sudo apt list qemu-user-static -a

script:
    - make build/debian.buster.armhf.cpio CONFIG_DEBIAN_ARCH=armhf
    - make build/debian.buster.i386.cpio CONFIG_DEBIAN_ARCH=i386
    - make test CONFIG_DISABLE_KVM=yes
