sudo: enabled
dist: bionic

language: minimal

install:
    - sudo apt-get update
    - make build-depends
    - sudo update-binfmts --disable
    - sudo rm /var/lib/binfmts/qemu-*
    - sudo sed -i 's/bionic/cosmic/g' /etc/apt/sources.list
    - sudo apt-get update
    - sudo apt-get install qemu-user-static
    - cat /proc/sys/fs/binfmt_misc/qemu-arm
    - cat /proc/sys/fs/binfmt_misc/qemu-riscv64

script:
    - make build/debian.buster.armhf.cpio CONFIG_DEBIAN_ARCH=armhf
    - make build/debian.buster.arm64.cpio CONFIG_DEBIAN_ARCH=arm64
    - make build/debian.buster.i386.cpio CONFIG_DEBIAN_ARCH=i386
    - make build/debian.buster.mipsel.cpio CONFIG_DEBIAN_ARCH=mipsel
    - make build/debian.unstableports.riscv64.cpio CONFIG_DEBIAN_ARCH=riscv64 CONFIG_DEBIAN=unstableports
    - make test CONFIG_DISABLE_KVM=yes

before_deploy:
    - git config --local user.name "Hamish Coleman"
    - git config --local user.email "hamish@zot.org"
    - git tag prerelease

deploy:
    provider: releases
    api_key: "$GITHUB_TOKEN"
    skip_cleanup: true
    overwrite: true
    file:
        - "build/debian.buster.armhf.cpio"
        - "build/debian.buster.arm64.cpio"
        - "build/debian.buster.i386.cpio"
        - "build/debian.buster.mipsel.cpio"
        - "build/debian.unstableports.riscv64.cpio"
