sudo: enabled
dist: xenial

language: minimal

# The recommended and tested build environment is Debian, so hack travis to
# be a Debian Stretch install
before_install:
    - sudo apt-get purge wireless-regdb
    - sudo apt-get install -y debian-archive-keyring
    - sudo rm -f /etc/apt/sources.list.d/*
    - echo "deb http://httpredir.debian.org/debian/ stretch main" |sudo tee /etc/apt/sources.list
    - sudo apt-get update
    - sudo apt-get dist-upgrade -y
    - sudo apt-get install -y debian-archive-keyring

install:
    - make build-depends
    - sudo apt-get install debian-archive-keyring

script:
    - make test CONFIG_DISABLE_KVM=yes
